// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8XupM160jQykTaNEsUyXtCG9pFm4x6PI',
    appId: '1:309845711634:web:8cbfee5b0c70424317b1cb',
    messagingSenderId: '309845711634',
    projectId: 'nitrvyuha',
    authDomain: 'nitrvyuha.firebaseapp.com',
    databaseURL: 'https://nitrvyuha-default-rtdb.firebaseio.com',
    storageBucket: 'nitrvyuha.firebasestorage.app',
    measurementId: 'G-D96S14SPCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXsbQJjvWyK6qS8Cy55Um95PxVlQXf3Q',
    appId: '1:309845711634:android:52b76711c72add5a17b1cb',
    messagingSenderId: '309845711634',
    projectId: 'nitrvyuha',
    databaseURL: 'https://nitrvyuha-default-rtdb.firebaseio.com',
    storageBucket: 'nitrvyuha.firebasestorage.app',
  );
}
