// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bEcIkEvCf1vdyu9EnLZutao8O_2jaHk',
    appId: '1:322778540049:web:aa7bd90c8d05f7241729b0',
    messagingSenderId: '322778540049',
    projectId: 'vyuha-1cdb8',
    authDomain: 'vyuha-1cdb8.firebaseapp.com',
    databaseURL: 'https://vyuha-1cdb8-default-rtdb.firebaseio.com',
    storageBucket: 'vyuha-1cdb8.firebasestorage.app',
    measurementId: 'G-YS3CFE3FXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe4xuC-khloM0-OjwQeE_cJF7P2l-hWms',
    appId: '1:322778540049:android:71658cfd56018e561729b0',
    messagingSenderId: '322778540049',
    projectId: 'vyuha-1cdb8',
    databaseURL: 'https://vyuha-1cdb8-default-rtdb.firebaseio.com',
    storageBucket: 'vyuha-1cdb8.firebasestorage.app',
  );
}
